enum TestMode {
  DEACTIVATED = 'DEACTIVATED',
  TEST_SUBUH = 'TEST_SUBUH',
  TEST_SYURUK = 'TEST_SYURUK',
  TEST_ZOHOR = 'TEST_ZOHOR',
  TEST_ASAR = 'TEST_ASAR',
  TEST_MAGHRIB = 'TEST_MAGHRIB',
  TEST_ISYAK = 'TEST_ISYAK',
}

export { TestMode };